routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::resource('basket', 'BasketController');

Route::get('/experiment-1', 'HomeController@index')->name('experiment-1');
Route::get('/experiment-2', 'HomeController@index2')->name('experiment-2');
Route::get('home', 'HomeController@show')->name('home-show');
Route::get('home-second', 'HomeController@second')->name('home-second');

Route::get('top-picks/{product}', 'ProductController@show')->name('top-picks-show');

Route::get('new-releases', 'ProductController@newReleases')->name('new-releases');
Route::get('new-releases/{product}', 'ProductController@show')->name('new-releases-show');

Route::get('mens', 'ProductController@mens')->name('mens');
Route::get('mens/{product}', 'ProductController@show')->name('mens-show');

Route::get('womens', 'ProductController@womens')->name('womens');
Route::get('womens/{product}', 'ProductController@show')->name('womens-show');

Route::get('children', 'ProductController@children')->name('children');
Route::get('children/{product}', 'ProductController@show')->name('children-show');

Route::get('sale', 'ProductController@sale')->name('sale');
Route::get('sale/{product}', 'ProductController@show')->name('sale-show');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Product;

class Product extends Model
{
    protected $fillable = ['id'];
    protected $table = 'products';

    public function basket() {
    	return $this->belongsTo(Basket::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function newReleases()
    {
        $products = Product::where('new_product', true)->paginate(5);

        $category = 'New Releases';

        return view('products.index', compact('products', 'category'));
    }

    public function mens()
    {
        $products = Product::where('category', 'mens')->paginate(5);

        $category = 'Mens';

        return view('products.index', compact('products', 'category'));
    }

    public function womens()
    {
        $products = Product::where('category', 'womens')->paginate(5);

        $category = 'Womens';

        return view('products.index', compact('products', 'category'));
    }

    public function children()
    {
        $products = Product::where('category', 'childrens')->paginate(5);

        $category = 'Childrens';

        return view('products.index', compact('products', 'category'));
    }

    public function sale()
    {
        $products = Product::whereNotNull('sale_price')->paginate(5);

        $category = 'Sale';

        return view('products.index', compact('products', 'category'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    { 
        return view('products.show', compact('product'));
    }
}

resources/views/products/index.blade.php
@extends('home')

@section('content')
	<h1 class="font-weight-light">{{ $category }}</h1>

	 <table class="table">
	    <tbody>
	        @foreach($products as $product) 
	            <tr class="text-center">
	            	<th>
		            	@if($category == 'New Releases')
		                	<a href="{{ route('new-releases-show', $product) }}">
		                		<img src="{{ $product->src }}"  height="200" width="400" alt="Image of {{ $product->name }}"/>
		                	</a>
	                	@elseif($category == 'Mens')
	                		<a href="{{ route('mens-show', $product) }}">
	                			<img src="{{ $product->src }}"  height="200" width="400" alt="Image of {{ $product->name }}"/>
	                		</a>
	                	@elseif($category == 'Womens')
							<a href="{{ route('womens-show', $product) }}">
								<img src="{{ $product->src }}"  height="200" width="400" alt="Image of {{ $product->name }}"/>
							</a>
	                	@elseif($category == 'Childrens')
	                		<a href="{{ route('children-show', $product) }}">
	                			<img src="{{ $product->src }}"  height="200" width="400" alt="Image of {{ $product->name }}"/>
	                		</a>
	                	@elseif($category == 'Sale')
							<a href="{{ route('sale-show', $product) }}">
								<img src="{{ $product->src }}"  height="200" width="400" alt="Image of {{ $product->name }}"/>
							</a>
	                	@endif
                	</th>

                	<td>
	                    <td>
	                    	{{ ucfirst($product->name) }}
	                    </td>  
	                </td>

	                <td>
	                    <td>
	                    	{{ ucfirst($product->category) }}
	                    </td>  

	                    @if($product->sale_price != null)
	                    	<td>
	                    		<text class="text-danger">
	                    			<strike>£{{ $product->price }}</strike>
	                    		</text>

	                    		£{{ $product->sale_price }}
	                    	</td>
	                    @else
	                    	<td>£{{ $product->price }}</td>  
	                    @endif
	                </td>

			 		<td>
			            @if($product->stock_amount < 5 && $product->stock_amount > 0)
			                <p class="text-danger">
			                    Only {{ $product->stock_amount }} left!
			                </p>
			            @elseif ($product->stock_amount == 0)
			                <p class="text-danger">
			                    Out of stock
			                </div>
			            @else
			                <p class="text-success">
			                    In stock - FREE DELIVERY!
			                </p>
			            @endif
			        </td>
	            </tr>
	        @endforeach
	    </tbody>
	</table>

	<div class="container">
		<div class="float-right">
			{{ $products->links() }}
		</div>
	</div>
@endsection

resources/views/products/sale.blade.php
{{-- @extends('home')

@section('content')
	<h1 class="font-weight-light">{{$category}}</h1>
	<h2> Sale </h2>
	 <table class="table">
	    <tbody>
	        @foreach($products as $product)  
	            <tr>
	                <th>IMAGE</th>

	                <th>
	                    <td>{{$product->name}}</td>  
	                    <td>£{{$product->price}}</td>  
	                    <td>{{ucfirst($product->category)}}</td>  
	                </th>
	            </tr>
	        </div>
	        @endforeach
	    </tbody>
	</table>
@endsection --}}

resources/views/products/show.blade.php
@extends('home')

@section('content')
	<div class="container">
		@include('flash::message')
	</div>



	<div class="container">
		<div class="row">
			<div class="col-md-6" style="padding-right:20px; border-right: 1px solid #ccc;">
				<img src="{{ $product->src }}"  height="250" width="500" alt="Image of {{ $product->name }}"/>
			</div>
			
			<div class="col-md-6">
				<h1>{{ $product->name }} - {{ ucfirst($product->category) }}</h1>
				<h2>£{{ $product->price }}</h2>

				<div class="row">
					<div class="col-md-12">
						@if($product->stock_amount < 10 && $product->stock_amount > 0)
							<div class="alert alert-danger text-center">
								Only {{ $product->stock_amount }} left!
							</div>
						@elseif ($product->stock_amount == 0)
							<div class="alert alert-danger text-center">
								Out of stock
							</div>
						@else
							<div class="alert alert-success text-center">
								In stock - FREE DELIVERY!
							</div>
						@endif
					</div>
				</div>

				@if($product->stock_amount != 0)
					<div class="row">
						<div class="col-md-12">
							<form method="POST" action="{{ !Auth::user() ? route('login') : route('basket.store') }}">
							@csrf

								<input class="input" type="hidden" name="product_id" value="{{ $product->id }}">
								<input class="input" type="hidden" name="user_id" value="{{ Auth::id() }}">

								<button type="submit" class="btn btn-block btn-primary">Add to Basket</button>
							</form>							
						</div>
					</div>
				@endif

				<hr>

				<p>{{ $product->description }}</h3>
			</div>
		</div>
	</div>
@endsection