routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::resource('basket', 'BasketController');

Route::get('/experiment-1', 'HomeController@index')->name('experiment-1');
Route::get('/experiment-2', 'HomeController@index2')->name('experiment-2');
Route::get('home', 'HomeController@show')->name('home-show');
Route::get('home-second', 'HomeController@second')->name('home-second');

Route::get('top-picks/{product}', 'ProductController@show')->name('top-picks-show');

Route::get('new-releases', 'ProductController@newReleases')->name('new-releases');
Route::get('new-releases/{product}', 'ProductController@show')->name('new-releases-show');

Route::get('mens', 'ProductController@mens')->name('mens');
Route::get('mens/{product}', 'ProductController@show')->name('mens-show');

Route::get('womens', 'ProductController@womens')->name('womens');
Route::get('womens/{product}', 'ProductController@show')->name('womens-show');

Route::get('children', 'ProductController@children')->name('children');
Route::get('children/{product}', 'ProductController@show')->name('children-show');

Route::get('sale', 'ProductController@sale')->name('sale');
Route::get('sale/{product}', 'ProductController@show')->name('sale-show');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/additional-styles.css') }}" rel="stylesheet">
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel fixed-top bg-light">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/home') }}">
                    {{ config('app.name') }}
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif
                            </li>
                        @else
                            <li class="nav-item">
                                @if(!Auth::user()->getBasket()->isEmpty())
                                    <a class="nav-link" href="{{ route('basket.index') }}">
                                        {{ __('My Basket') }} 

                                        @if(App\Basket::where('user_id', Auth::id())->count() > 0)
                                            <span class="badge badge-primary">{{ App\Basket::where('user_id', Auth::id())->count() }}</span>
                                        @endif
                                    </a>
                                @endif
                            </li>
                            
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
    </div>

    <br>

    @if(\Request::is('register') || \Request::is('login') || \Request::is('basket'))
        @yield('content')   
    @endif
</body>
</html>